---
- name: Setup for the Docker's Environment
  hosts: localhost
  tasks:
    - name: Install packages to install docker
      when: ansible_os_family == "Debian"
      become: yes
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker APT GPG key
      when: ansible_os_family == "Debian"
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      when: ansible_os_family == "Debian"
      become: yes
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present
        filename: "docker"

    - name: Install docker engine (Debian/Ubuntu)
      when: ansible_os_family == "Debian"
      become: yes
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Add Docker yum repository
      when: ansible_os_family == "RedHat"
      become: yes
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: "/etc/yum.repos.d/"
        owner: "root"
        group: "root"
        mode: 0644

    - name: Install docker engine (RHEL/CentOS)
      when: ansible_os_family == "RedHat"
      become: yes
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes
      register: docker_install_result_rh
    
    - name: docker service restart
      when: docker_install_result_rh.changed == true
      become: yes
      service:
        name: docker
        state: started
        enabled: true

    - name: adding local user '{{ lookup('env','USER') }}' to group docker
      become: yes
      user:
        name: "{{ lookup('env','USER') }}"
        groups: docker
        append: yes