---
- name: Setup for the Serverspec's Environment
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Get ruby rpm file when centos version is lower than 8 (RHEL/CentOS~7)
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version <= '7'
      become: yes
      get_url:
        url: https://github.com/feedforce/ruby-rpm/releases/download/2.7.2/ruby-2.7.2-1.el7.centos.x86_64.rpm
        dest: "{{ ansible_env.HOME }}"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: 0644

    - name: yum localinstall ruby rpm (RHEL/CentOS~7)
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version <= '7'
      become: yes
      yum:
        name: "{{ ansible_env.HOME }}/ruby-2.7.2-1.el7.centos.x86_64.rpm"
        state: present

    - name: Install ruby (RHEL/CentOS8~)
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version > '7'
      become: yes
      yum:
        name: ruby
        state: present

    - name: Install ruby, ruby-bundler, ruby-full (Debian/Ubuntu)
      when: ansible_os_family == "Debian"
      become: yes
      apt:
        name:
          - ruby
          - ruby-bundler
          - ri
          - libgmp-dev
          - ruby-dev
          - ruby2.7-dev
          - ruby2.7-doc
          - ruby-full
        state: present

    - name: Dependencies version Problem solve (Debian/Ubuntu)
      when: ansible_os_family == "Debian"
      lineinfile:
        dest: "../Gemfile"
        line: "{{ item }}"
        insertafter: EOF
      with_items:
        - "gem 'net-ssh', '>= 6.0.2'"
        - "gem 'ed25519', '>= 1.2', '< 2.0'"
        - "gem 'bcrypt_pbkdf', '>= 1.0', '< 2.0'"

    - name: Install gems using a Gemfile
      bundler:
        state: present
        gemfile: ../Gemfile