---
- name: Ansible_ssh_conf
  hosts: localhost
  gather_facts: no
  tasks:
    - name: PasswordAuthentication change from no to yes
      become: yes
      replace:
        dest: /etc/ssh/sshd_config
        regexp: 'PasswordAuthentication no'
        replace: 'PasswordAuthentication yes'
        backup: yes
      register: result

    - name: sshd restart to apply "PasswordAuthentication"
      become: yes
      service:
        name: sshd
        state: restarted
      changed_when: result.changed == true