---
- name: Setup for the Ansible's Environment
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Add /etc/hosts
      blockinfile: |
        dest=/etc/hosts
        content="{{nodes}}"

    - name: Install sshpass for Authentication (RHEL/CentOS)
      when: ansible_os_family == "RedHat"
      yum:
        name: sshpass
        state: present

    - name: Install vim-enhanced (RHEL/CentOS)
      when: ansible_os_family == "RedHat"
      #when: ansible_facts['distribution'] == "CentOS"
      yum:
        name: vim-enhanced
        state: present

    - name: Install git (RHEL/CentOS)
      when: ansible_os_family == "RedHat"
      #when: ansible_facts['distribution'] == "CentOS"
      yum:
        name: git
        state: present

    - name: Install sshpass for Authentication (Debian/Ubuntu)
      when: ansible_os_family == "Debian"
      apt:
        name: sshpass
        state: present

    - name: Install vim-enhanced (Debian/Ubuntu)
      when: ansible_os_family == "Debian"
      #when: ansible_facts['distribution'] == "Ubuntu"
      apt:
        name: "vim"
        state: present

    - name: Install git (Debian/Ubuntu)
      when: ansible_os_family == "Debian"
      #when: ansible_facts['distribution'] == "Ubuntu"
      apt:
        name: "git"
        state: present

    - name: Download pathogen.vim
      get_url:
        url: https://tpo.pe/pathogen.vim
        dest: /home/vagrant/.vim/autoload/pathogen.vim
        mode: 0644
        owner: vagrant
        group: vagrant

    - name: Download vim-ansible-yaml.tar.gz
      get_url:
        url: https://github.com/chase/vim-ansible-yaml/archive/v1.0.tar.gz
        dest: /home/vagrant/.vim/bundle/v1.0.tar.gz

    - name: Unarchive vim-ansible-yaml.tar.gz
      unarchive:
        src: /home/vagrant/.vim/bundle/v1.0.tar.gz
        dest: /home/vagrant/.vim/bundle/
        mode: 0755

    - name: Configure vimrc
      lineinfile:
        dest: /home/vagrant/.vimrc
        line: "{{ item }}"
      with_items:
        - "set number"
        - "execute pathogen#infect()"
        - "syntax on"
        - "autocmd FileType yaml setlocal ai ts=2 sw=2 et"

    - name: Configure Bashrc
      lineinfile:
        dest: /home/vagrant/.bashrc
        line: "{{ item }}"
      with_items:
        - "alias vi='vim'"
        - "alias ans='ansible'"
        - "alias anp='ansible-playbook'"

    - name: Copy Ansible ansible.cfg file to home direction
      copy:
        src: ansible.cfg
        dest: /home/vagrant
        owner: vagrant
        group: vagrant
        mode: 0664

    - name: Copy Ansible hosts.ini file to home direction
      copy:
        src: hosts.ini
        dest: /home/vagrant
        owner: vagrant
        group: vagrant
        mode: 0664