---
- name: Setup for the Ansible's Environment
  hosts: localhost
  gather_facts: yes
  vars: 
    local_home: "{{ lookup('env','HOME') }}"
    local_user: "{{ lookup('env','USER') }}"
  tasks:
    - name: Add /etc/hosts
      become: yes
      blockinfile: |
        dest=/etc/hosts
        content="{{ nodes }}"

    - name: Install sshpass for Authentication (RHEL/CentOS)
      when: ansible_os_family == "RedHat"
      become: yes
      yum:
        name: sshpass
        state: present

    - name: Install vim-enhanced (RHEL/CentOS)
      when: ansible_os_family == "RedHat"
      become: yes
      yum:
        name: vim-enhanced
        state: present

    - name: Install git (RHEL/CentOS)
      when: ansible_os_family == "RedHat"
      become: yes
      yum:
        name: git
        state: present

    - name: Install sshpass for Authentication (Debian/Ubuntu)
      when: ansible_os_family == "Debian"
      become: yes
      apt:
        name: sshpass
        state: present

    - name: Install vim-enhanced (Debian/Ubuntu)
      when: ansible_os_family == "Debian"
      become: yes
      apt:
        name: "vim"
        state: present

    - name: Install git (Debian/Ubuntu)
      when: ansible_os_family == "Debian"
      become: yes
      apt:
        name: "git"
        state: present

    - name: Copy pathogen.vim file to .vim/autoload
      become: yes
      copy:
        src: custom/pathogen.vim
        dest: "{{ local_home }}/.vim/autoload/"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        mode: 0664

    - name: Copy vim-ansible-yaml.tar.gz file to .vim/bundle
      become: yes
      copy:
        src: custom/vim-ansible-yaml-1.0.tar.gz
        dest: "{{ local_home }}/.vim/bundle/"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        mode: 0664

    - name: Unarchive vim-ansible-yaml.tar.gz
      become: yes
      unarchive:
        src: "{{ local_home }}/.vim/bundle/vim-ansible-yaml-1.0.tar.gz"
        dest: "{{ local_home }}/.vim/bundle/"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        mode: 0755
    
    - name: Remove custom folder
      file:
        path: custom
        state: absent

    - name: Configure vimrc
      lineinfile:
        dest: "{{ local_home }}/.vimrc"
        line: "{{ item }}"
      with_items:
        - "set number"
        - "execute pathogen#infect()"
        - "syntax on"
        - "autocmd FileType yaml setlocal ai ts=2 sw=2 et"

    - name: Configure Bashrc
      lineinfile:
        dest: "{{ local_home }}/.bashrc"
        line: "{{ item }}"
      with_items:
        - "alias vi='vim'"
        - "alias ans='ansible'"
        - "alias anp='ansible-playbook'"

    - name: Copy Ansible ansible.cfg file to home direction
      copy:
        src: ansible.cfg
        dest: "{{ local_home }}"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        mode: 0664

    - name: Copy Ansible hosts.ini file to home direction
      copy:
        src: hosts.ini
        dest: "{{ local_home }}"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        mode: 0664