---
- name: Setup for the Kubespray's Environment
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Install pip for Kubespray (RHEL/CentOS)
      when: ansible_os_family == "RedHat"
      yum:
        name: python-pip
        state: present

    - name: Install pip3 for Kubespray (Debian/Ubuntu)
      when: ansible_os_family == "Debian"
      apt:
        name: python3-pip
        state: present